config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :offers do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:destroy, :update, :edit, :index, :show]
  get 'my_reservations', to: 'reservations#my_reservations', as: 'my_reservations'

  get 'my_offers', to: 'offers#my_offers', as: 'my_offers'
  get 'my_offers/:id', to: 'offers#my_offers_show', as: 'my_offers_show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many_attached :photos
  validates :photos, presence: true

  validates :photos, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_location,
    against: [:location],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :offer
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :offers, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :photo])
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def index
    if params[:query].present? && Offer.search_by_location(params[:query]).size > 0
      @offers = Offer.search_by_location(params[:query])
    else
      @offers = Offer.all
    end
    # if params[:query].present?
    #   raise
    #   @offers = Offer.where("location ILIKE ?", "%#{params[:query]}%")
    # else
    #   @offers = Offer.all
    # end

    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude
      }
    end
  end

  def my_offers
    @user = current_user.id
    @offers = Offer.where(user_id: @user)
  end

  def show
    @offer = Offer.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user_id = current_user.id
    if @offer.save
      redirect_to my_offers_path
    else
      render 'offers/new', status: :unprocessable_entity
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params) # Will raise ActiveModel::ForbiddenAttributesError

    redirect_to my_offers_path
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to my_offers_path, status: :see_other
  end

  def my_offers_show
    show
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :location, :price_per_night, photos: [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @offer = Offer.last
    @offers = Offer.first(3)
    # @offers = Offer.search_by_location(params[:query])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_offer, only: [:new, :create]

  # My requests
  def index
    # @user = current_user.id
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.offer = @offer
    @reservation.user = current_user
    if @reservation.save
      redirect_to my_reservations_path
    else
      render 'offers/show', status: :unprocessable_entity
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.update(reservation_params)
    redirect_to my_reservations_path
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    redirect_to my_reservations_path, status: :see_other
  end

  # def confirm
  #   @reservation = Reservation.find(params[:id])
  #   @reservation.confirmed = true
  # end

  # Las reservas que yo hago
  def my_reservations
      @reservations = Reservation.all
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date_checkin, :date_checkout, :guests, :confirmed)
  end

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HostMyPet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <link rel="icon" href= "<%= image_path "host-my-pet-logo.png" %>">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%# <p class="notice"><%= notice </p> %>
    <%# <p class="alert"><%= alert </p> %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for(offer) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :location, input_html: {data: {location_autocomplete_target: "location"}, class: "d-none"},  wrapper_html: {data: {controller: "location-autocomplete",location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]} } %>
  <%= f.input :price_per_night %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/offers/edit.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1576201836106-db1758fd1c97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1>Edit your place </h1>
  </div>
</div>

<div class="container-my-reservations">
  <div class="cards-container">
      <div class="container-show-header">
        <div class="botton-show">
          <%= link_to "Back to My Offers", offers_path, class: "btn btn-primary" %>
        </div>
      </div>
  </div>

  <div class="container mt-4">
    <div class="row">
      <div class="col-6 m-auto">
        <div class="flat-form form-container">
            <h1> Edit your place details</h1>
            <div class="mt-3">
              <%= render "form", offer: @offer %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="container-my-reservations">
  <h3>Search results</h3>
  <p>Update your search</p>
  <div class="form-group mt-3 mb-3 col-12 formulario">

    <%= form_with url: offers_path, method: :get, class: "d-flex" do %>
      <div class="input-group">
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Location" %>
      </div>
      <%# <div class="input-group">
        <%= number_field :guests, in: 1..20, step: 0.5, class: "form-control", placeholder: "Number of guests" %>
      <%# </div> %>
      <div class="input-group pl-3">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="cards-container search-index">
    <div class="cards cards-index">
      <% @offers.each do |offer| %>

      <div class="card-trip">
        <% if offer.photos[0] != nil %>
          <%= cl_image_tag offer.photos[0].key  %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1543051932-6ef9fecfbc80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=424&q=80" />
        <% end %>

        <div class="card-trip-infos">
          <div class="card-content">
            <div class="card-section">
              <h2><%= offer.title %></h2>
            </div>
            <div class="reservation-content">
              <p><em><%= offer.description %></em></p>
              <p>Host: <%= offer.user.full_name %></p>
              <p>Location: <%= offer.location %></p>
              <p>$<%= offer.price_per_night %> per night</p>
            </div>
            <div class="reservation-actions">
              <%= link_to "Details", offer_path(offer), class:"ms-3 text-success"  %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div id="map" style="width: 100%; height: 600px;" data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/offers/my_offers.html.erb
<div class="container-my-reservations">

  <div class="boris-card mb-5 p-0">
    <img src="https://images.unsplash.com/photo-1571988840298-3b5301d5109b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" />
    <div class="card-boris-infos p-3">
      <h2>My Offers</h2>
      <p>Check your current <strong>offers</strong> </p>
    </div>
  </div>

  <div class="cards-container">
      <div class="container-show-header">
        <div class="botton-show button-offers">
          <%= link_to "Create new offer", new_offer_path, class:"btn btn-primary" %>
        </div>
      </div>
  </div>

  <div class="cards">
    <% @offers.each do |offer| %>
    <div class="card-trip">
      <% if offer.photos[0] != nil %>
        <%= cl_image_tag offer.photos[0].key  %>
      <% else %>
        <img src="https://images.unsplash.com/photo-1543051932-6ef9fecfbc80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=424&q=80" />
      <% end %>

      <%# <% offer.photos.each do |photo| %>
        <%# <%= cl_image_tag photo.key %>
      <%# <% end %>
      <div class="card-trip-infos">
        <div class="card-content">
          <div class="card-section">
            <h2><%= offer.title %></h2>
          </div>
          <div class="reservation-content">
            <p><em><%= offer.description %></em></p>
            <p>Host: <%= offer.user.full_name %></p>
            <p>Location: <%= offer.location %></p>
            <p>$<%= offer.price_per_night %> per night</p>
          </div>
          <div class="reservation-actions">
            <%= link_to "Details", my_offers_show_path(offer), class:"ms-3 text-success"  %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/offers/my_offers_show.html.erb
<div class="fotos d-flex m-4">
  <div class="foto m-2">
    <img src="<%= cl_image_path @offer.photos[0].key %>"
      class="d-block w-100"
      alt="Canyon at Nigh"/>
    </div>

      <div class="foto ml-2 m-2">
    <img src="<%= cl_image_path @offer.photos[1].key %>"
      class="d-block w-100"
      alt="Canyon at Nigh"/>
    </div>
</div>

  <div class="container-show-reservations mt-0">

      <div class="container container-reservation-content">
        <%# <div class="botton-show">
          <%= link_to "Back to My Reservations", my_reservations_path, class: "btn btn-primary" %>
        <%# </div> %>

        <div class="my-reservation-details">

          <div class= "d-flex justify-content-between">
            <div>
              <h2><%= @offer.title %></h2>
              <p> <small><%= @offer.location %> </small></p>
              <hr><br>
            </div>

            <div class="botton-show cancellation-show">
              <%= link_to "Edit offer", edit_offer_path, class: "btn btn-primary" %>
              <%= link_to "Delete", offer_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>
              <%= link_to "Booking requests", reservations_path, class: "btn btn-primary" %>
            </div>

          </div>
          <p> Hosted by: <%= @offer.user.full_name %> </p>
          <p><em>A bit more about the place:</em></p>
          <p> <%= @offer.description %> </p>
        </div>

      </div>
  </div>

app/views/pages/home.html.erb
<div class="banner-home-container" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('bannerhome.jpg') %>);">

  <div class="container container-home">
    <div class="banner-home">
      <h1> <strong>Host my Pet</strong> </h1>
      <p><span data-controller="typed-js"></span></p>
      <%# <a class="btn btn-flat" href="#">Apply now</a> %>
      <div class="formulario">
        <div class="form-group">
          <%= form_with url: offers_path, method: :get do %>
            <div class="input-group">
              <%= text_field_tag :query, params[:query], class: "form-control", placeholder: 'Search by location' %>
            </div>
            <div class="input-group">
              <select id="inputState" class="form-control">
                <option selected >Number of pets</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
              </select>
            </div>
            <%= submit_tag "Search", class: "btn btn-primary m-0 border-0 ", id:"basic-addon2" %>
          <% end %>
        </div>
      </div>
            <!--
            <%= simple_form_for(@offer) do |f| %>
              <%= f.input :location, input_html: {data: {location_autocomplete_target: "location"}, class: "d-none"},  wrapper_html: {data: {controller: "location-autocomplete",location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]} } %>
            <% end %>
          <%= link_to "Search", offers_path, class: "btn btn-primary" %>
          -->
    </div>
  </div>
</div>

<div class="container-my-reservations">
  <div class="cards-container">
      <h3 class="mb-3">Recommended</h3>
      <div class="container-show-header">
        <%# <div class="botton-show">
          <%= link_to "Add a Movie", new_list_bookmark_path(@list), class: "btn btn-success" %>
        <%# </div> %>
      </div>
  </div>

  <div class="cards">
    <% @offers.each do |offer| %>
    <div class="card-trip">
        <% if offer.photos[0] != nil %>
            <%= cl_image_tag offer.photos[0].key  %>
        <% else %>
            <img src="https://images.unsplash.com/photo-1543051932-6ef9fecfbc80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=424&q=80" />
        <% end %>
      <div class="card-trip-infos">
        <div class="card-content">
          <div class="card-section">
            <div class="card-section-title">
              <h2><%= offer.title %></h2>
              <h2 class="card-home-pricing"><em>$<%= offer.price_per_night.round %></em></h2>
            </div>
            <p><small><%= offer.location %></small></p>
          </div>
          <div class="reservation-content">
            <p><%= offer.description %></p>
            <p><small>Hosted by: <%= offer.user.full_name %></small></p>
          </div>
          <div class="reservation-actions">
            <%= link_to "More details", offer_path(offer), class:"ms-3 text-success" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1554456854-55a089fd4cb2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1>My Booking Requests </h1>
  </div>
</div>

<div class="container-my-reservations">
  <div class="cards-container">
      <div class="container-show-header">
        <%# <div class="botton-show">
          <%= link_to "Add a Movie", new_list_bookmark_path(@list), class: "btn btn-success" %>
        <%# </div> %>
      </div>
  </div>

  <div class="cards">
    <% @reservations.each do |reservation| %>

      <% if current_user.id == reservation.user_id %>
      <% else %>
        <div class="card-trip">
          <% if reservation.offer.photos[0] != nil %>
            <%= cl_image_tag reservation.offer.photos[0].key  %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1543051932-6ef9fecfbc80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=424&q=80" />
          <% end %>
          <div class="card-trip-infos">
            <div class="card-content">
              <div class="card-section">
                <h2>Booking for <%= reservation.offer.title %></h2>
              </div>
              <div class="reservation-content">
                <p>Guest: <%= reservation.user.email %></p>
                <p>Check in: <%= reservation.date_checkin %></p>
                <p>Check out: <%= reservation.date_checkout %></p>
                <p>Number of Guests: <%= reservation.guests %></p>
              </div>
              <div class="reservation-actions">
                <%= simple_form_for reservation do |r| %>
                  <%= r.input :confirmed %>
                  <%# <%= link_to "Confirmed", reservations_path, class: "form-check-input", type: "checkbox", value: "" %>
                  <%= r.submit "Update", class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/reservations/my_reservations.html.erb
<%# <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1534361960057-19889db9621e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1>My Reservations </h1>
  </div>
</div>
 %>


<div class="container-my-reservations">

  <div class="boris-card mb-5 p-0">
  <img src="https://images.unsplash.com/photo-1585664811087-47f65abbad64?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80" />
    <div class="card-boris-infos p-3">
    <h2>My reservations</h2>
    <p>Check your upcoming <strong> bookings</strong> </p>
  </div>

</div>

  <div class="cards-container">
      <div class="container-show-header">
        <%# <div class="botton-show">
          <%= link_to "Add a Movie", new_list_bookmark_path(@list), class: "btn btn-success" %>
        <%# </div> %>
      </div>
  </div>

  <div class="cards mt-3">
    <% @reservations.each do |reservation| %>
      <% if current_user.id == reservation.user_id %>
        <div class="card-trip">
          <% if reservation.offer.photos[0] != nil %>
              <%= cl_image_tag reservation.offer.photos[0].key  %>
          <% else %>
              <img src="https://images.unsplash.com/photo-1543051932-6ef9fecfbc80?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=424&q=80" />
          <% end %>

          <div class="card-trip-infos">
            <div class="card-content">
              <div class="card-section">
                <h2>Booking for <%= reservation.offer.title %></h2>
                <%# <div class="rating">
                  <p>5</p>
                  <i class="fa-solid fa-star"></i>
                </div> %>
              </div>

              <div class="reservation-content">
                <p>Check in: <%= reservation.date_checkin %></p>
                <p>Check out: <%= reservation.date_checkout %></p>
                <p>Guests: <%= reservation.guests %></p>
                <p>Reservation status:
                  <% if reservation.confirmed %>
                    <%= "Confirmed" %>
                  <% else %>
                    <%= "Not Confirmed" %>
                  <% end %>
                </p>
              </div>

              <div class="reservation-actions">
                  <%= link_to "Cancel", reservation_path(reservation), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"ms-3 text-success" %>
                  <%= link_to "Edit", edit_reservation_path(reservation), class:"ms-3 text-success" %>
                  <%= link_to "Details", reservation_path(reservation), class:"ms-3 text-success"  %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/reservations/show.html.erb
  <% if @reservation.offer.photos[0] != nil %>
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @reservation.offer.photos[0].key %>);">

  <% else %>
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1600456899121-68eda5705257?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1257&q=80);">
  <% end %>

    <div class="container">
        <h1>Reservation details for <%= @reservation.offer.title %></h1>
    </div>
  </div>

  <div class="container-show-reservations">

      <div class="container container-reservation-content">

        <%# <div class="botton-show">
          <%= link_to "Back to My Reservations", my_reservations_path, class: "btn btn-primary" %>
        <%# </div> %>

        <div class="my-reservation-details">
          <h2><%= @reservation.offer.title %></h2>
          <p> <small><%= @reservation.offer.location %> </small></p>
          <hr><br>
          <p> Hosted by: <%= @reservation.offer.user.full_name %> </p>
          <p> <%= @reservation.offer.description %> </p>
          <p>Reservation status:
              <% if @reservation.confirmed %>
                <%= "Confirmed" %>
              <% else %>
                <%= "Not Confirmed" %>
              <% end %>
            </p>
        </div>

        <div class="botton-show cancellation-show">
          <%= link_to "Request cancellation", reservation_path(@reservation), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-primary" %>
        </div>

      </div>

      <div class="container">
        <div class="row">
          <div class="col-10 m-auto">
            <div class="flat-form form-container">
                <h3> $ <%= @reservation.offer.price_per_night %> <small>per night</small></h3>
                <div class="mt-3">
                    <%= simple_form_for @reservation do |r| %>
                    <%= r.input :date_checkin, as: :date, html5: true %>
                    <%= r.input :date_checkout, as: :date, html5: true%>
                    <%= r.input :guests %>
                    <%= r.button :submit, class: "btn btn-primary" %>
                    <% end %>
                </div>
            </div>
          </div>
        </div>
      </div>

  </div>

app/views/shared/_bannerhome.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('bannerhome.jpg') %>);">
  <div class="container">
  <div class="banner-home">
    <h1> <strong>Home my Pet</strong> </h1>
    <p>The only way your pet will feel like home</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "host-my-pet-logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.key != nil %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "avatar-logout.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end dropdown-navbar" aria-labelledby="navbarDropdown">
              <div class="welcome-user">
                <p><strong>Hola</strong></p>
                <small><%= current_user.email %></small>
              </div>
              <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center"><i class="fa-solid fa-suitcase-rolling"></i> <%= link_to "My reservations", my_reservations_path, class: "dropdown-item" %></li>
                <% if current_user.offers.size == 0 %>
                  <li class="list-group-item d-flex justify-content-between align-items-center"><%= link_to "Become a host", new_offer_path, class: "dropdown-item" %></li>
                <% end %>
                <% if current_user.offers.size > 0 %>
                  <li class="list-group-item d-flex justify-content-between align-items-center"><i class="fa-solid fa-house"></i> <%= link_to "My offers", my_offers_path, class: "dropdown-item" %></li>
                  <li class="list-group-item d-flex justify-content-between align-items-center"><i class="fa-solid fa-paw"></i> <%= link_to "My Requests", reservations_path, class: "dropdown-item" %></li>
                <% end %>
                <li class="list-group-item d-flex justify-content-between align-items-center"><i class="fa-solid fa-sliders"></i> <%= link_to "My account", edit_user_registration_path, class: "dropdown-item" %></li>
                <li class="list-group-item d-flex justify-content-between align-items-center"><i class="fa-solid fa-right-from-bracket"></i> <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
              </ul>

            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>